# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170925_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', tinymce.models.HTMLField(blank=True, help_text='Enter a short description.', null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('poster', models.FileField(blank=True, null=True, upload_to='')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='poster',
        ),
    ]
