# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170925_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='button_text',
            field=models.CharField(blank=True, default='Register now', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, help_text='Please enter a link to register for the event', null=True),
        ),
    ]
