# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroun_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, help_text='Please enter a link for learn more button', null=True)),
                ('button_text', models.CharField(blank=True, default='Learn More', max_length=100, null=True)),
                ('link2', models.URLField(blank=True, help_text='Please enter a link for learn more button', null=True)),
                ('button_text2', models.CharField(blank=True, default='Learn More', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_image', models.ImageField(blank=True, help_text='this will be a sliding images on the homepage', null=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('carousel_text', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeIcons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, default='fa-heart', help_text="Please write in which icon you'd like, ie fa-phone. Check <a href='http://fontawesome.io/icons/'>here</a> for icons.", max_length=100, null=True)),
            ],
        ),
    ]
