# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='this will be a sliding images on the homepage', null=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('carousel_text', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='HomeIcons',
            new_name='HomeIcon',
        ),
        migrations.DeleteModel(
            name='Home_Images',
        ),
    ]
