# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20170925_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
