# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_subheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='subheader',
            name='button_text',
            field=models.CharField(blank=True, default='Learn More', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subheader',
            name='link',
            field=models.URLField(blank=True, help_text='Please enter a link for learn more button', null=True),
        ),
    ]
