# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20170925_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='small rounded image on homepage', null=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
