# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20170926_0304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmallImage',
        ),
    ]
